openapi: 3.0.0
info:
  title: Azure API Management - OpenID Connect Providers
  description: Use these REST APIs for performing operations on OpenId Connect Provider
    entity associated with your Azure API Management deployment. API Management
    allows you to access APIs secured with token from [OpenID Connect Provider
    ](http://openid.net/connect/) to be accessed from the Developer Console.
  version: 2017-03-01
security:
  - apim_key: []
paths:
  /openidConnectProviders:
    get:
      tags:
        - OpenIdConnectProviders
      operationId: OpenIdConnectProvider_List
      description: Lists all OpenID Connect Providers.
      parameters:
        - name: $filter
          in: query
          required: false
          description: >-
            | Field | Supported operators    | Supported
            functions                         |

            |-------|------------------------|---------------------------------------------|

            | id    | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |

            | name  | ge, le, eq, ne, gt, lt | substringof, contains, startswith, endswith |
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/TopQueryParameter
        - $ref: ./apimanagement.json#/components/parameters/SkipQueryParameter
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        "200":
          description: Lists of all the OpenId Connect Providers.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenIdConnectProviderCollection"
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-odata: "#/components/schemas/OpenidConnectProviderContract"
  "/openidConnectProviders/{opid}":
    get:
      tags:
        - OpenIdConnectProviders
      operationId: OpenIdConnectProvider_Get
      description: Gets specific OpenID Connect Provider.
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        "200":
          description: The response body contains the specified OpenId Connect Provider
            entity.
          headers:
            ETag:
              description: Current entity state version. Should be treated as opaque and
                used to make conditional HTTP requests.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
    put:
      tags:
        - OpenIdConnectProviders
      operationId: OpenIdConnectProvider_CreateOrUpdate
      description: Creates or updates the OpenID Connect Provider.
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenidConnectProviderContract"
        description: Create parameters.
        required: true
      responses:
        "200":
          description: OpenIdConnect Provider was successfully updated.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
        "201":
          description: OpenIdConnect Provider was successfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenidConnectProviderContract"
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
    patch:
      tags:
        - OpenIdConnectProviders
      operationId: OpenIdConnectProvider_Update
      description: Updates the specific OpenID Connect Provider.
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - name: If-Match
          in: header
          required: true
          description: The entity state (Etag) version of the OpenID Connect Provider to
            update. A value of "*" can be used for If-Match to unconditionally
            apply the operation.
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OpenidConnectProviderUpdateContract"
        description: Update parameters.
        required: true
      responses:
        "204":
          description: OpenId Connect Provider was successfully updated.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
    delete:
      tags:
        - OpenIdConnectProviders
      operationId: OpenIdConnectProvider_Delete
      description: Deletes specific OpenID Connect Provider of the API Management service
        instance.
      parameters:
        - $ref: "#/components/parameters/OpenIdConnectIdParameter"
        - name: If-Match
          in: header
          required: true
          description: The entity state (Etag) version of the OpenID Connect Provider to
            delete. A value of "*" can be used for If-Match to unconditionally
            apply the operation.
          schema:
            type: string
        - $ref: ./apimanagement.json#/components/parameters/ApiVersionParameter
      responses:
        "204":
          description: OpenId Connect Provider was successfully deleted.
        default:
          description: Error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: ./apimanagement.json#/definitions/ErrorResponse
servers:
  - url: "{apimBaseUrl}"
    variables:
      apimBaseUrl:
        description: The management endpoint of the API Management service, for example
          https://myapimservice.management.azure-api.net.
        x-ms-skip-url-encoding: true
        default: ""
components:
  parameters:
    OpenIdConnectIdParameter:
      name: opid
      in: path
      required: true
      description: Identifier of the OpenID Connect Provider.
      x-ms-parameter-location: method
      schema:
        type: string
        maxLength: 256
        pattern: ^[^*#&+:<>?]+$
  securitySchemes:
    apim_key:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    OpenIdConnectProviderCollection:
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/OpenidConnectProviderContract"
          description: Page values.
        count:
          type: integer
          description: Total number of entities
        nextLink:
          type: string
          description: Next page link if any.
      description: Paged OpenIdProviders list representation.
    OpenidConnectProviderContract:
      properties:
        id:
          type: string
          description: Identifier of the OpenId Connect Provider.
      allOf:
        - $ref: "#/components/schemas/OpenidConnectProviderContractProperties"
      description: OpenId Connect Provider details.
    OpenidConnectProviderContractProperties:
      properties:
        name:
          type: string
          description: User-friendly OpenID Connect Provider name.
          maxLength: 50
        description:
          type: string
          description: User-friendly description of OpenID Connect Provider.
        metadataEndpoint:
          type: string
          description: Metadata endpoint URI.
        clientId:
          type: string
          description: Client ID of developer console which is the client application.
        clientSecret:
          type: string
          description: Client Secret of developer console which is the client application.
      required:
        - name
        - metadataEndpoint
        - clientId
      description: OpenID Connect Providers Contract.
    OpenidConnectProviderUpdateContract:
      properties:
        name:
          type: string
          description: User-friendly OpenID Connect Provider name.
          maxLength: 50
        description:
          type: string
          description: User-friendly description of OpenID Connect Provider.
        metadataEndpoint:
          type: string
          description: Metadata endpoint URI.
        clientId:
          type: string
          description: Client ID of developer console which is the client application.
        clientSecret:
          type: string
          description: Client Secret of developer console which is the client application.
      description: Parameters supplied to the Update OpenID Connect Provider operation.